2021-07-02 09:28:25,924 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-07-02 09:28:25,925 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2021-07-02 09:28:25,927 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-07-02 09:28:26,617 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2021-07-02 09:28:26,617 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2021-07-02 09:28:26,625 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2021-07-02 09:28:26,626 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
